### ISSUE TITLE
Optional RWX

### ISSUE THREAD

**Issue by jortel** [konveyor/tackle2-operator#140]
Integration with: https://github.com/konveyor/tackle2-hub/issues/148

Goals:
- Only create CACHE PVC when supported by the cluster.
- Discontinue support for Addon CR to list volumes to be mounted.
- Support concept of a _general_ CACHE (RWX) volume that is mounted on the Hub (by the operator) and each task pod (by the task manager).

Changes:
- Add new operator setting: `rwx_supported` (bool).  Default: true
- Rename all `maven-` settings to `rwx-`.
- Rename all `tackle-maven-` resources to `tackle-cache-`.
- The maven PVC no longer injected into the windup addon CR.
- When RWX is supported:
  - Create PV and PVC `tackle-cache-` and mount in the Hub.
  - Set RWX_SUPPORTED Envar in the Hub and UI.
  - Set CACHE_PVC in the Hub to the name of the PVC.
  - Mount the bucket volume RWO in the Hub only when it does not exist.
 - When RWX not supported:
   - Mount the bucket volume RWO in the Hub.  **Existing PVC must not be updated to preserve data in upgrades.
- The addon CRD needs to be updated.
- The _admin_ addon no longer installed. CR to be removed.

**Comment by jmontleon** [comment]
For clarification, after discussion:
- The `maven-` PVC will be created `rwx-` if `rwx_supported` is set `true`.
- On upgrade we will ensure the PVC with the old name is deleted (`state: absent`) and create the new rwx PVC
- Going forward we wll create the bucket volume as `RWO`.
- If it already exists `RWX` we will not attempt to update it, as it is moderately complex (we'd have to stop or remove the deployment, ensure the PV reclaim policy is set to retain, delete the PVC and recreate it since the access mode is immutable), and not without risk.
- The admin CR will be `state: absent` in all cases.

**Comment by jortel** [comment]
@jmontleon I agree with your summary.  I edit the description to reflect our discussion re: s/RWX/CACHE in places.
